# Generated by Django 3.0.5 on 2020-04-19 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload_date', models.DateField(help_text='업로드 날짜')),
                ('order_number', models.BigIntegerField(db_index=True, help_text='주문번호')),
                ('customer_name', models.TextField(help_text='구매자명')),
                ('count', models.IntegerField(help_text='구매 갯수')),
                ('receiver_name', models.TextField(help_text='수취인 명')),
                ('hitomi_price', models.IntegerField(help_text='히토미 가')),
            ],
            options={
                'verbose_name': 'purchase - 구매내역',
                'verbose_name_plural': 'purchase - 구매내역',
                'db_table': 'purchase',
            },
        ),
    ]
