# Generated by Django 3.0.5 on 2020-04-19 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Margin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_date', models.DateField(db_index=True, help_text='정산일')),
                ('customer_name', models.TextField(help_text='구매자명')),
                ('order_number', models.BigIntegerField(db_index=True, help_text='주문번호', unique=True)),
                ('hitomi_price', models.IntegerField(help_text='히토미 가')),
                ('amount_of_payment', models.IntegerField(help_text='결제금액')),
                ('payment_fee', models.IntegerField(help_text='결제수수료')),
                ('connection_fee', models.IntegerField(help_text='연동수수료')),
                ('margin', models.IntegerField(help_text='마진')),
            ],
            options={
                'verbose_name': 'magin - 마진 내역',
                'verbose_name_plural': 'magin - 마진 내역',
                'db_table': 'margin',
            },
        ),
    ]
