# Generated by Django 3.0.5 on 2020-04-19 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Sales',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('standard_date', models.DateField(db_index=True, help_text='정산일')),
                ('order_number', models.TextField(db_index=True, help_text='주문번호')),
                ('product_number', models.TextField(help_text='상품 주문번호')),
                ('product_name', models.TextField(db_index=True, help_text='상품명')),
                ('category', models.TextField(help_text='배송비/상품주문')),
                ('customer_name', models.TextField(help_text='구매자명')),
                ('amount_of_payment', models.IntegerField(help_text='결제금액')),
                ('payment_fee', models.IntegerField(help_text='결제수수료')),
                ('connection_fee', models.IntegerField(help_text='연동수수료')),
            ],
            options={
                'verbose_name': 'sales - 정산내역',
                'verbose_name_plural': 'sales - 정산내역',
                'db_table': 'sales',
                'unique_together': {('standard_date', 'order_number', 'product_number', 'product_name')},
            },
        ),
    ]
